### ISSUE TITLE
a confusing issue

### ISSUE THREAD

**Issue by lilhongxy** [HKUNLP/ChunkLlama#8] opened 2024-03-29 07:42 UTC
**_cos, sin = self.rotary_emb(value_states, seq_len=kv_seq_len)
ValueError: too many values to unpack (expected 2)_**

I follow the instructions in the Full inference code,bu then I encounter this issue.
How can I fix this?

**Comment by ChenxinAn-fdu** [comment] 2024-03-29 16:08
This error is usually caused by calling  `replace_with_chunkllama()` after  `model.from_pretrained()`.  Make sure `replace_with_chunkllama()` is called before initializing the model.  If it cannot solve the error, please provide more details.

**Comment by lilhongxy** [comment] 2024-03-31 14:37
```
from transformers import AutoTokenizer, LlamaTokenizer, LlamaForCausalLM, AutoModelForCausalLM
from chunkllama_attn_replace import replace_with_chunkllama
import torch

replace_with_chunkllama(pretraining_length=4096)

tokenizer = LlamaTokenizer.from_pretrained("path_to_Llama-2-7b-hf", trust_remote_code=True)
model = LlamaForCausalLM.from_pretrained("path_to_Llama-2-7b-hf", trust_remote_code=True, torch_dtype=torch.bfloat16)
inputs = tokenizer("Long...docs\n Q: How to extend the context window of LLMs? ", return_tensors="pt")

output_ids = model.generate(**inputs, max_length=128)[0]
print(tokenizer.decode(output_ids))
```

I just precisely followde the inference instructions,but the issue remained...

**Comment by Mooler0410** [comment] 2024-04-01 01:12
> ```
> from transformers import AutoTokenizer, LlamaTokenizer, LlamaForCausalLM, AutoModelForCausalLM
> from chunkllama_attn_replace import replace_with_chunkllama
> import torch
> 
> replace_with_chunkllama(pretraining_length=4096)
> 
> tokenizer = LlamaTokenizer.from_pretrained("path_to_Llama-2-7b-hf", trust_remote_code=True)
> model = LlamaForCausalLM.from_pretrained("path_to_Llama-2-7b-hf", trust_remote_code=True, torch_dtype=torch.bfloat16)
> inputs = tokenizer("Long...docs\n Q: How to extend the context window of LLMs? ", return_tensors="pt")
> 
> output_ids = model.generate(**inputs, max_length=128)[0]
> print(tokenizer.decode(output_ids))
> ```
> 
> I just precisely followde the inference instructions,but the issue remained...

Could you please check your transformers version? RoPE api for llama is changed again after 4.38. (Actually, It always changes...from 4.35 to 4.36, to 4.37, to 4.38 ... almost each recent transformers release has a new RoPE implementation for Llama..😓)

**Comment by ChenxinAn-fdu** [comment] 2024-04-01 06:21
Hey guys, the code works in my environment.  My transformer version is `4.37.2`
```
from transformers import AutoTokenizer, LlamaTokenizer, LlamaForCausalLM, AutoModelForCausalLM
from chunkllama_github import replace_with_chunkllama
import torch

model_path = "path/to/llama2"

replace_with_chunkllama(pretraining_length=4096)

tokenizer = LlamaTokenizer.from_pretrained(model_path, trust_remote_code=True)
model = LlamaForCausalLM.from_pretrained(model_path, trust_remote_code=True, torch_dtype=torch.bfloat16).to("cuda:0")
inputs = tokenizer("Long...docs\n Q: How to extend the context window of LLMs? ", return_tensors="pt").to("cuda:0")

output_ids = model.generate(**inputs, max_length=128)[0]
print(tokenizer.decode(output_ids))
```

**Comment by ChenxinAn-fdu** [comment] 2024-04-01 06:51
Please use Flash Attention for processing longer input:
`model = LlamaForCausalLM.from_pretrained(model_path, attn_implementation="flash_attention_2", trust_remote_code=True, torch_dtype=torch.bfloat16).to(device)`

**Comment by lilhongxy** [comment] 2024-04-01 08:05
thank you all guys !!!😄 
finally get success
It is my torch version that caused the issue, previous version is 2.2.1+cu118

success environment:
` torch_version:2.0.1+cu118`
`transformers_version:4.37.2`

**Comment by ChenxinAn-fdu** [comment] 2024-04-02 10:20
If there are no further questions or follow-up discussions, I will close this issue shortly. Thank you all for your contributions and participation.

**Closed as completed** 2024-04-03 06:06 UTC

**Comment by MarsMeng1994** [comment] 2024-04-30 08:41
infer is corret, but when finetune, it comes out again
